{% set name = "waf" %}
{% set version = "2.0.20" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://waf.io/waf-{{ version }}.tar.bz2
  sha256: cce635c2d1a0f93b4f5b811e0452a35b8066e8ccd78632447f5be24c4c3f1a63

build:
  number: 0
  script:
    - python waf-light --make-waf --tool=swig,cython,boost,use_config
    - cp waf "${PREFIX}/bin"     # [unix]
    - copy waf "%SCRIPTS%"   # [win]

requirements:
  build:    
    - {{ compiler('c') }}
  host:
    - python

  run:
    - python

test:
  files:
    - wscript

  commands:
    - waf --help
    - waf configure
    - waf build

about:
  home: https://waf.io
  license: BSD 3-Clause
  summary: A build automation tool.

extra:
  recipe-maintainers:
    - jakirkham
    - nicoddemus
    - tarcisiofischer
    - dfroger
