{% set name = "waf" %}
{% set version = "2.0.18" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://waf.io/waf-{{ version }}.tar.bz2
  sha256: 263d7ad4a75fd278399a1eae3eff6e8256a27617b3231b48e9b8992d1b6c7064

build:
  number: 0
  script:
    - python waf-light --make-waf --tool=swig,cython,boost,use_config
    - cp waf "${PREFIX}/bin"     # [unix]
    - copy waf "%SCRIPTS%"   # [win]

requirements:
  build:    
    - {{ compiler('c') }}
  host:
    - python

  run:
    - python

test:
  files:
    - wscript

  commands:
    - waf --help
    - waf configure
    - waf build

about:
  home: https://waf.io
  license: BSD 3-Clause
  summary: A build automation tool.

extra:
  recipe-maintainers:
    - jakirkham
    - nicoddemus
    - tarcisiofischer
    - dfroger
