{% set name = "waf" %}
{% set version = "2.1.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://waf.io/waf-{{ version }}.tar.bz2
  sha256: 4a47a431b86d5c42fa23b8474aaf752384dcaed65fe9e6aa1f518c103d38a7d1
  patches:
    - clang_arm64.patch

build:
  number: 0
  script:
    - python waf-light --make-waf --tool=swig,cython,boost,use_config
    - cp waf "${PREFIX}/bin"     # [unix]
    - copy waf "%SCRIPTS%"   # [win]

requirements:
  build:    
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python

  run:
    - python

test:
  files:
    - wscript

about:
  home: https://waf.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A build automation tool.
  description: >
    Waf is a Python-based framework for configuring, compiling and installing
    applications with automatic build order, dependency detection, and parallel
    task execution.
  doc_url: https://waf.io/book/
  dev_url: https://gitlab.com/ita1024/waf

extra:
  recipe-maintainers:
    - jakirkham
    - nicoddemus
    - tarcisiofischer
    - dfroger
