# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "dIv41DUNja8w0pKwshvMxv334rZ+OptWuYzzrD/SDkmsOZklppdB50LeWiHq4fbh9omlL9G+y8v738wQZvp8yyULGn9dYVH01VLjBMvhpKY1eyjFHYqBWh2EVeBWdao+ZA5Y82A/vJGBGZ9OQQnQC3GIQDxpduWUeoavL7v+S1nZsD+VOxkPr9X1V2kH1IikAdtu04r5UDRw/nC28+EQNJ0Ar6fE96BQJQLSa6RFNzYfN3+IDo3ijntK4iamaazuVawx0p0VnNhlLv898n84ucRz1BkMzpTfCivtlsMFNY6wa90XqoBXHQe/gfVX7NWNcqeUwWYs6bzVNcmPFiJtBgPKUQMu5eV0F+9TFuiKoPExaNTBp/XL4Th8GRbZvYJyUAFE+6HVOE6D5fU5diEIyaiZ/S4hnq1yiXbW3ZRr6SY+iPPAQu645/oD6tGpo2IwqxJ4+BjVe6yQe0E/FUWiQM9k//Z/GiBrQPVr/aitIqWnGQ4tpTDC+9m2J2NSVhMX/dFaTliS37EkvDl1+oJNonWYQxjyL3+Zblcs9Rc3LEOQJtSKWf/Y4uVIUT0+GMCaBVZJAAOnwzmntt/PJJuPAFIfhAmMA7m2Uke6OLUz1eskcIvNFo3KRivlRLkFvzdTipXMtWDT6KMHVEGwicrU8KO2UbJUUMh4Cnd9BkOwXqQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
