travis:
  secure:
    BINSTAR_TOKEN: fwk5FPLczY/6iJqeApQv3OaH9XJZm769Rqrho60p2p5WjKoXkWb1R7jpPPizKZFlcdHXfo8I5fQpvHWJDHXMczqv1Y0LuPsMsr6smgKZ5Pp85014AP0bFaPygmaATgsuVw69jVmJ3SJDu3uoA23OEm4nh2tycBCANfE2mpc0RHlDMuvlzC4rOF+Pn0jYIQfa1PmRamDXEJhFT06ahajmE0rkECgTvNDW2taRvYhspuCtf7Zd/e9Dl5S32QiyjTgauCVZeJozT3VqXVK3m/vvBRLZuCSr1zS+q/L/LYqVjaf2m+hLzvnDXAueUUmO1CWB4y2DNtIPS41QN8f8NCOSQiFhFwn2Au79ejFbejIR8EnUuV91NeIFyajJy4Kh4eVOjQSQI0/k1fBWAfXA1CkHnW/e1LvUlUIxnr9hHKckXNChhvQHOl+Se3z8nmbMjsU46DwbZYXTHXbW7a3I78kuzEM03FdNa7x6QV1HB7V2Ca2dLratsq+MrQzfqHoHeLnwgPfBAlDWDSCC0zaMMzoWy6UUOBdRvRYWYBGCrSOpGTCUzsYJKLHZX45o1wSJW2xogFBqkI2ygh9Npu0gAQsCL32tMZ7kQkz98cUewngriOi3Zv5OcgVmF9kykNq0EbJ9s5WtwE5bbLqn7uq4AFURQishh95ALaUXBu5iWoT3T44=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
